// Paw — Tauri application entry point.
// All helper functions (mail, keychain, weather) have been moved to commands:: modules.
// Channel bridge commands are generated by commands::channels::channel_commands! macro.

// ── Paw Atoms (constants, error types) ────────────────────────────────────
pub mod atoms;

// ── Paw Agent Engine ───────────────────────────────────────────────────
pub mod engine;

// ── Paw Command Modules (Systems layer) ───────────────────────────────
pub mod commands;

use tauri::Manager;

/// One-time startup DB housekeeping: purge empty sessions, prune oversized ones.
fn startup_housekeeping(state: &commands::state::EngineState) {
    use atoms::constants::{
        CHAT_SESSION_MAX_MESSAGES, STARTUP_EMPTY_SESSION_MAX_AGE_SECS,
        STARTUP_STALE_SESSION_MAX_AGE_DAYS,
    };

    log::info!("[startup] Running DB housekeeping…");

    // 1. Delete empty sessions older than 1 hour
    match state
        .store
        .cleanup_empty_sessions(STARTUP_EMPTY_SESSION_MAX_AGE_SECS, None)
    {
        Ok(n) if n > 0 => log::info!("[startup] Purged {} empty sessions", n),
        Err(e) => log::warn!("[startup] Empty session cleanup failed: {}", e),
        _ => {}
    }

    // 2. Prune large sessions: any session with > MAX messages gets trimmed
    match state.store.list_sessions_filtered(500, None) {
        Ok(sessions) => {
            let stale_cutoff =
                chrono::Utc::now() - chrono::Duration::days(STARTUP_STALE_SESSION_MAX_AGE_DAYS);
            let stale_cutoff_str = stale_cutoff.to_rfc3339();

            for s in &sessions {
                // Only prune sessions that are stale OR over the message cap
                let is_stale = s.updated_at.as_str() < stale_cutoff_str.as_str();
                let is_large = s.message_count > CHAT_SESSION_MAX_MESSAGES;

                if is_stale || is_large {
                    let keep = if is_stale {
                        // Stale sessions: keep fewer messages (just enough to resume)
                        (CHAT_SESSION_MAX_MESSAGES / 2).max(20)
                    } else {
                        CHAT_SESSION_MAX_MESSAGES
                    };
                    match state.store.prune_session_messages(&s.id, keep) {
                        Ok(n) if n > 0 => {
                            log::info!(
                            "[startup] Pruned {} messages from session '{}' (kept {}, stale={})",
                            n, s.id, keep, is_stale
                        )
                        }
                        Err(e) => log::warn!("[startup] Prune failed for session {}: {}", s.id, e),
                        _ => {}
                    }
                }
            }
        }
        Err(e) => log::warn!("[startup] Session listing for pruning failed: {}", e),
    }

    log::info!("[startup] DB housekeeping complete");
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Install the rustls crypto provider before any TLS usage.
    // Required since rustls 0.23 — without this, agent tasks panic
    // when they try to auto-detect the provider.
    rustls::crypto::ring::default_provider()
        .install_default()
        .expect("Failed to install rustls CryptoProvider");

    // Load custom data root from ~/.paw/storage.conf BEFORE opening the DB.
    engine::paths::load_data_root_from_conf();

    let engine_state =
        commands::state::EngineState::new().expect("Failed to initialize Paw Agent Engine");

    // Initialize the cognitive event bus (§47.6 observability infrastructure).
    // Must happen before any gated_search / working_memory calls.
    engine::engram::cognitive_event::init();

    tauri::Builder::default()
        .manage(engine_state)
        .plugin(
            tauri_plugin_log::Builder::new()
                .target(tauri_plugin_log::Target::new(
                    tauri_plugin_log::TargetKind::LogDir {
                        file_name: Some("openpawz".into()),
                    },
                ))
                .max_file_size(5_000_000)
                // Global default: only Info+ from third-party crates
                .level(log::LevelFilter::Info)
                // App crate: keep Debug for engine diagnostics
                .level_for("paw_temp", log::LevelFilter::Debug)
                .build(),
        )
        .plugin(tauri_plugin_sql::Builder::default().build())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .setup(|app| {
            // ── Startup DB housekeeping (runs once, non-blocking) ─────────
            {
                let app_handle = app.handle().clone();
                std::thread::spawn(move || {
                    if let Some(state) = app_handle.try_state::<commands::state::EngineState>() {
                        startup_housekeeping(&state);
                    }
                });
            }

            // ── n8n engine auto-start (background, non-blocking) ────────
            {
                let app_handle = app.handle().clone();
                tauri::async_runtime::spawn(async move {
                    // Wait for the app to finish initializing
                    tokio::time::sleep(std::time::Duration::from_secs(8)).await;

                    // Only auto-start if the user has previously enabled n8n
                    let config = engine::n8n_engine::load_config(&app_handle).unwrap_or_default();
                    if !config.enabled {
                        log::debug!("[n8n] Auto-start skipped — n8n not enabled");
                        return;
                    }

                    log::info!("[n8n] Auto-starting integration engine...");
                    match commands::n8n::engine_n8n_ensure_ready(app_handle).await {
                        Ok(endpoint) => {
                            log::info!(
                                "[n8n] Integration engine ready at {} (mode={:?})",
                                endpoint.url,
                                endpoint.mode
                            );
                        }
                        Err(e) => {
                            log::warn!("[n8n] Auto-start failed (non-fatal): {}", e);
                        }
                    }
                });
            }

            let app_handle = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_secs(10)).await;
                log::info!("[heartbeat] Cron heartbeat started (60s interval)");
                loop {
                    engine::tasks::run_cron_heartbeat(&app_handle).await;
                    tokio::time::sleep(std::time::Duration::from_secs(60)).await;
                }
            });

            // ── Engram memory maintenance (consolidation + decay + GC) ─────
            // Runs every 5 minutes in the background. Consolidates episodic
            // memories into semantic triples, applies Ebbinghaus decay, and
            // garbage-collects weak memories.
            let app_handle_engram = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                // Wait 30 seconds for app to stabilize before first maintenance
                tokio::time::sleep(std::time::Duration::from_secs(30)).await;
                log::info!("[engram] Memory maintenance started (300s interval)");
                loop {
                    if let Some(state) = app_handle_engram.try_state::<crate::commands::state::EngineState>() {
                        let emb_client = state.embedding_client();
                        match engine::engram::bridge::run_maintenance(
                            &state.store,
                            emb_client.as_ref(),
                            7.0,   // half_life_days
                            1,     // gc_importance_threshold
                        ).await {
                            Ok(report) => {
                                log::info!(
                                    "[engram] Maintenance complete: {} triples, {} decayed, {} GC'd",
                                    report.consolidation.triples_created,
                                    report.memories_decayed,
                                    report.memories_gc,
                                );

                                // §4.5 Self-Healing: inject gap prompts into all active agents'
                                // working memory so they become aware of contradictions, stale
                                // data, or incomplete schemas detected during consolidation.
                                if !report.gap_prompts.is_empty() {
                                    log::info!(
                                        "[engram] Injecting {} gap prompts into active agents",
                                        report.gap_prompts.len()
                                    );
                                    // Collect arcs briefly under the parking_lot lock, then release
                                    let agent_states: Vec<(String, std::sync::Arc<tokio::sync::Mutex<engine::engram::CognitiveState>>)> = {
                                        let cs_map = state.cognitive_states.lock();
                                        cs_map.iter().map(|(k, v)| (k.clone(), std::sync::Arc::clone(v))).collect()
                                    };
                                    for (agent_id, cs_arc) in &agent_states {
                                        let mut cs = cs_arc.lock().await;
                                        cs.inject_gap_prompts(&report.gap_prompts);
                                        log::debug!(
                                            "[engram] Gap prompts injected for agent '{}'",
                                            agent_id
                                        );
                                    }
                                }
                            }
                            Err(e) => {
                                log::warn!("[engram] Maintenance failed (non-fatal): {}", e);
                            }
                        }
                    }
                    tokio::time::sleep(std::time::Duration::from_secs(300)).await;
                }
            });
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            // ── Mail (himalaya bridge) ──
            commands::mail::write_himalaya_config,
            commands::mail::read_himalaya_config,
            commands::mail::remove_himalaya_account,
            commands::mail::fetch_emails,
            commands::mail::fetch_email_content,
            commands::mail::send_email,
            commands::mail::list_mail_folders,
            commands::mail::move_email,
            commands::mail::delete_email,
            commands::mail::set_email_flag,
            // ── Utility (keychain, weather, db crypto, lock screen) ──
            commands::utility::keyring_has_password,
            commands::utility::keyring_delete_password,
            commands::utility::fetch_weather,
            commands::utility::get_db_encryption_key,
            commands::utility::has_db_encryption_key,
            commands::utility::check_keychain_health,
            commands::utility::lock_screen_has_passphrase,
            commands::utility::lock_screen_set_passphrase,
            commands::utility::lock_screen_verify_passphrase,
            commands::utility::lock_screen_remove_passphrase,
            commands::utility::lock_screen_system_auth,
            commands::utility::lock_screen_system_available,
            // ── Chat & Sessions ──
            commands::chat::engine_chat_send,
            commands::chat::engine_chat_history,
            commands::chat::engine_chat_abort,
            commands::chat::engine_sessions_list,
            commands::chat::engine_session_rename,
            commands::chat::engine_session_delete,
            commands::chat::engine_session_clear,
            commands::chat::engine_session_cleanup,
            commands::chat::engine_session_compact,
            commands::chat::engine_approve_tool,
            // ── Engine Config & Sandbox ──
            commands::config::engine_sandbox_check,
            commands::config::engine_sandbox_get_config,
            commands::config::engine_sandbox_set_config,
            commands::config::engine_get_config,
            commands::config::engine_get_daily_spend,
            commands::config::engine_set_config,
            commands::config::engine_upsert_provider,
            commands::config::engine_remove_provider,
            commands::config::engine_status,
            commands::config::engine_auto_setup,
            // ── Storage Paths ──
            commands::config::engine_storage_get_paths,
            commands::config::engine_storage_set_data_root,
            // ── Agent Files (Soul / Persona) ──
            commands::agent::engine_agent_file_list,
            commands::agent::engine_agent_file_get,
            commands::agent::engine_agent_file_set,
            commands::agent::engine_agent_file_delete,
            commands::agent::engine_list_all_agents,
            commands::agent::engine_create_agent,
            commands::agent::engine_delete_agent,
            // ── Memory (Long-term Semantic) ──
            commands::memory::engine_memory_store,
            commands::memory::engine_memory_search,
            commands::memory::engine_memory_stats,
            commands::memory::engine_memory_delete,
            commands::memory::engine_memory_list,
            commands::memory::engine_get_memory_config,
            commands::memory::engine_set_memory_config,
            commands::memory::engine_test_embedding,
            commands::memory::engine_embedding_status,
            commands::memory::engine_embedding_pull_model,
            commands::memory::engine_ensure_embedding_ready,
            commands::memory::engine_memory_backfill,
            commands::memory::engine_working_memory_save,
            commands::memory::engine_working_memory_restore,
            commands::memory::engine_memory_purge_user,
            // ── Skill Vault ──
            commands::skills::engine_skills_list,
            commands::skills::engine_skill_set_enabled,
            commands::skills::engine_skill_bulk_enable,
            commands::skills::engine_skill_set_credential,
            commands::skills::engine_skill_get_credential,
            commands::skills::engine_skill_delete_credential,
            commands::skills::engine_skill_revoke_all,
            commands::skills::engine_skill_get_instructions,
            commands::skills::engine_skill_set_instructions,
            // ── Onboarding (Phase 4) ──
            commands::skills::engine_is_onboarding_complete,
            commands::skills::engine_set_onboarding_complete,
            // ── Community Skills (skills.sh) ──
            commands::skills::engine_community_skills_list,
            commands::skills::engine_community_skills_browse,
            commands::skills::engine_community_skills_search,
            commands::skills::engine_community_skill_install,
            commands::skills::engine_community_skill_remove,
            commands::skills::engine_community_skill_set_enabled,
            commands::skills::engine_community_skill_set_agents,
            // ── TOML Manifest Skills (Phase F.1) ──
            commands::skills::engine_toml_skills_scan,
            commands::skills::engine_toml_skill_install,
            commands::skills::engine_toml_skill_uninstall,
            // ── PawzHub Registry (Phase F.4) ──
            commands::skills::engine_pawzhub_search,
            commands::skills::engine_pawzhub_browse,
            commands::skills::engine_pawzhub_install,
            // ── Skill Outputs (Phase F.2) ──
            commands::skills::engine_list_skill_outputs,
            // ── Skill Wizard (Phase F.5) ──
            commands::skill_wizard::engine_wizard_generate_toml,
            commands::skill_wizard::engine_wizard_publish_url,
            // ── Skill Storage (Phase F.6) ──
            commands::skills::engine_skill_store_list,
            // ── Trading ──
            commands::trade::engine_trading_history,
            commands::trade::engine_trading_summary,
            commands::trade::engine_trading_policy_get,
            commands::trade::engine_trading_policy_set,
            // ── Positions (Stop-Loss / Take-Profit) ──
            commands::trade::engine_positions_list,
            commands::trade::engine_position_close,
            commands::trade::engine_position_update_targets,
            // ── Text-to-Speech ──
            commands::tts::engine_tts_speak,
            commands::tts::engine_tts_get_config,
            commands::tts::engine_tts_set_config,
            commands::tts::engine_tts_transcribe,
            // ── Tasks (Kanban Board) ──
            commands::task::engine_tasks_list,
            commands::task::engine_task_create,
            commands::task::engine_task_update,
            commands::task::engine_task_delete,
            commands::task::engine_task_move,
            commands::task::engine_task_activity,
            commands::task::engine_task_set_agents,
            commands::task::engine_task_run,
            commands::task::engine_tasks_cron_tick,
            // ── Flows (Visual Pipelines) ──
            commands::flows::engine_flows_list,
            commands::flows::engine_flows_get,
            commands::flows::engine_flows_save,
            commands::flows::engine_flows_delete,
            commands::flows::engine_flow_runs_list,
            commands::flows::engine_flow_run_create,
            commands::flows::engine_flow_run_update,
            commands::flows::engine_flow_run_delete,
            commands::flows::engine_flow_direct_http,
            commands::flows::engine_flow_direct_mcp,
            // ── Channel Bridges (80 commands: 10 channels × 8 ops) ──────────
            // Functions generated by channel_commands! macro in commands/channels.rs.
            // Telegram ──
            commands::channels::engine_telegram_start,
            commands::channels::engine_telegram_stop,
            commands::channels::engine_telegram_status,
            commands::channels::engine_telegram_get_config,
            commands::channels::engine_telegram_set_config,
            commands::channels::engine_telegram_approve_user,
            commands::channels::engine_telegram_deny_user,
            commands::channels::engine_telegram_remove_user,
            // Discord ──
            commands::channels::engine_discord_start,
            commands::channels::engine_discord_stop,
            commands::channels::engine_discord_status,
            commands::channels::engine_discord_get_config,
            commands::channels::engine_discord_set_config,
            commands::channels::engine_discord_approve_user,
            commands::channels::engine_discord_deny_user,
            commands::channels::engine_discord_remove_user,
            // IRC ──
            commands::channels::engine_irc_start,
            commands::channels::engine_irc_stop,
            commands::channels::engine_irc_status,
            commands::channels::engine_irc_get_config,
            commands::channels::engine_irc_set_config,
            commands::channels::engine_irc_approve_user,
            commands::channels::engine_irc_deny_user,
            commands::channels::engine_irc_remove_user,
            // Slack ──
            commands::channels::engine_slack_start,
            commands::channels::engine_slack_stop,
            commands::channels::engine_slack_status,
            commands::channels::engine_slack_get_config,
            commands::channels::engine_slack_set_config,
            commands::channels::engine_slack_approve_user,
            commands::channels::engine_slack_deny_user,
            commands::channels::engine_slack_remove_user,
            // Matrix ──
            commands::channels::engine_matrix_start,
            commands::channels::engine_matrix_stop,
            commands::channels::engine_matrix_status,
            commands::channels::engine_matrix_get_config,
            commands::channels::engine_matrix_set_config,
            commands::channels::engine_matrix_approve_user,
            commands::channels::engine_matrix_deny_user,
            commands::channels::engine_matrix_remove_user,
            // Mattermost ──
            commands::channels::engine_mattermost_start,
            commands::channels::engine_mattermost_stop,
            commands::channels::engine_mattermost_status,
            commands::channels::engine_mattermost_get_config,
            commands::channels::engine_mattermost_set_config,
            commands::channels::engine_mattermost_approve_user,
            commands::channels::engine_mattermost_deny_user,
            commands::channels::engine_mattermost_remove_user,
            // Nextcloud ──
            commands::channels::engine_nextcloud_start,
            commands::channels::engine_nextcloud_stop,
            commands::channels::engine_nextcloud_status,
            commands::channels::engine_nextcloud_get_config,
            commands::channels::engine_nextcloud_set_config,
            commands::channels::engine_nextcloud_approve_user,
            commands::channels::engine_nextcloud_deny_user,
            commands::channels::engine_nextcloud_remove_user,
            // Nostr ──
            commands::channels::engine_nostr_start,
            commands::channels::engine_nostr_stop,
            commands::channels::engine_nostr_status,
            commands::channels::engine_nostr_get_config,
            commands::channels::engine_nostr_set_config,
            commands::channels::engine_nostr_approve_user,
            commands::channels::engine_nostr_deny_user,
            commands::channels::engine_nostr_remove_user,
            // Twitch ──
            commands::channels::engine_twitch_start,
            commands::channels::engine_twitch_stop,
            commands::channels::engine_twitch_status,
            commands::channels::engine_twitch_get_config,
            commands::channels::engine_twitch_set_config,
            commands::channels::engine_twitch_approve_user,
            commands::channels::engine_twitch_deny_user,
            commands::channels::engine_twitch_remove_user,
            // Web Chat ──
            commands::channels::engine_webchat_start,
            commands::channels::engine_webchat_stop,
            commands::channels::engine_webchat_status,
            commands::channels::engine_webchat_get_config,
            commands::channels::engine_webchat_set_config,
            commands::channels::engine_webchat_approve_user,
            commands::channels::engine_webchat_deny_user,
            commands::channels::engine_webchat_remove_user,
            // WhatsApp ──
            commands::channels::engine_whatsapp_start,
            commands::channels::engine_whatsapp_stop,
            commands::channels::engine_whatsapp_status,
            commands::channels::engine_whatsapp_get_config,
            commands::channels::engine_whatsapp_set_config,
            commands::channels::engine_whatsapp_approve_user,
            commands::channels::engine_whatsapp_deny_user,
            commands::channels::engine_whatsapp_remove_user,
            // ── Orchestrator: Projects ──
            commands::project::engine_projects_list,
            commands::project::engine_project_create,
            commands::project::engine_project_update,
            commands::project::engine_project_delete,
            commands::project::engine_project_set_agents,
            commands::project::engine_project_messages,
            commands::project::engine_project_run,
            // ── Browser Profiles & Sandbox ──
            commands::browser::engine_browser_get_config,
            commands::browser::engine_browser_set_config,
            commands::browser::engine_browser_create_profile,
            commands::browser::engine_browser_delete_profile,
            // ── Screenshots ──
            commands::browser::engine_screenshots_list,
            commands::browser::engine_screenshot_get,
            commands::browser::engine_screenshot_delete,
            // ── Per-Agent Workspaces ──
            commands::browser::engine_workspaces_list,
            commands::browser::engine_workspace_files,
            commands::browser::engine_workspace_delete,
            // ── Network Policy (Outbound Domain Allowlist) ──
            commands::browser::engine_network_get_policy,
            commands::browser::engine_network_set_policy,
            commands::browser::engine_network_check_url,
            // ── Tailscale (Remote Access) ──
            commands::tailscale::engine_tailscale_status,
            commands::tailscale::engine_tailscale_get_config,
            commands::tailscale::engine_tailscale_set_config,
            commands::tailscale::engine_tailscale_serve_start,
            commands::tailscale::engine_tailscale_serve_stop,
            commands::tailscale::engine_tailscale_funnel_start,
            commands::tailscale::engine_tailscale_funnel_stop,
            commands::tailscale::engine_tailscale_connect,
            commands::tailscale::engine_tailscale_disconnect,
            // ── Webhook Server (Phase D) ──
            commands::webhook::engine_webhook_start,
            commands::webhook::engine_webhook_stop,
            commands::webhook::engine_webhook_status,
            commands::webhook::engine_webhook_get_config,
            commands::webhook::engine_webhook_set_config,
            commands::webhook::engine_webhook_regenerate_token,
            // ── n8n Integration ──
            commands::n8n::engine_n8n_get_config,
            commands::n8n::engine_n8n_set_config,
            commands::n8n::engine_n8n_test_connection,
            commands::n8n::engine_n8n_list_workflows,
            commands::n8n::engine_n8n_trigger_workflow,
            // ── n8n Engine Lifecycle (Phase 0) ──
            commands::n8n::engine_n8n_ensure_ready,
            commands::n8n::engine_n8n_mcp_status,
            commands::n8n::engine_n8n_mcp_refresh,
            commands::n8n::engine_n8n_get_status,
            commands::n8n::engine_n8n_get_engine_config,
            commands::n8n::engine_n8n_set_engine_config,
            commands::n8n::engine_n8n_health_check,
            commands::n8n::engine_n8n_shutdown,
            // ── Community Nodes (MCP bridge) ──
            commands::n8n::engine_n8n_community_packages_list,
            commands::n8n::engine_n8n_community_packages_install,
            commands::n8n::engine_n8n_community_packages_uninstall,
            commands::n8n::engine_n8n_community_packages_cancel,
            commands::n8n::engine_n8n_deploy_mcp_workflow,
            // ── NCNodes Discovery (Phase 3) ──
            commands::n8n::engine_n8n_search_ncnodes,
            // ── n8n Credential Management ──
            commands::n8n::engine_n8n_package_credential_schema,
            commands::n8n::engine_n8n_create_credential,
            // ── Ollama Model Management (Phase 4) ──
            commands::ollama::engine_ollama_list_models,
            commands::ollama::engine_ollama_has_model,
            commands::ollama::engine_ollama_pull_model,
            commands::ollama::engine_ollama_create_model,
            commands::ollama::engine_ollama_setup_worker,
            // ── Integration Credentials (Phase 2.5) ──
            commands::n8n::engine_integrations_test_credentials,
            commands::n8n::engine_integrations_save_credentials,
            commands::n8n::engine_integrations_get_credentials,
            // ── Credential Status & Provisioning (Phase 3) ──
            commands::n8n::engine_integrations_credential_status,
            commands::n8n::engine_integrations_provision,
            // ── Automation Templates (Phase 2.7) ──
            commands::automations::engine_automations_activate_template,
            commands::automations::engine_automations_list,
            commands::automations::engine_automations_toggle,
            commands::automations::engine_automations_delete,
            // ── Agent Queries (Phase 2.9) ──
            commands::queries::engine_queries_execute,
            commands::queries::engine_queries_history,
            commands::queries::engine_queries_clear_history,
            // ── Safety Guardrails (Phase 3.5) ──
            commands::guardrails::engine_guardrails_get_rate_limits,
            commands::guardrails::engine_guardrails_set_rate_limit,
            commands::guardrails::engine_guardrails_get_permissions,
            commands::guardrails::engine_guardrails_get_agent_permissions,
            commands::guardrails::engine_guardrails_set_permission,
            commands::guardrails::engine_guardrails_log_action,
            commands::guardrails::engine_guardrails_get_audit_log,
            commands::guardrails::engine_guardrails_clear_audit,
            commands::guardrails::engine_guardrails_check_token_expiry,
            commands::guardrails::engine_guardrails_update_token_info,
            // ── Integration Action Log (Phase 4) ──
            commands::action_log::engine_action_log_record,
            commands::action_log::engine_action_log_list,
            commands::action_log::engine_action_log_stats,
            commands::action_log::engine_action_log_clear,
            // ── Unified Audit Log ──
            commands::audit::engine_audit_query,
            commands::audit::engine_audit_stats,
            commands::audit::engine_audit_verify_chain,
            // ── Compliance Export ──
            commands::export::engine_compliance_export,
            commands::export::engine_compliance_export_to_file,
            // ── Tool Bridge & Remapping (Phase 5) ──
            commands::tool_bridge::engine_tools_remap,
            commands::tool_bridge::engine_tools_by_service,
            commands::tool_bridge::engine_tools_get_agent_assignment,
            commands::tool_bridge::engine_tools_set_agent_service,
            // ── Health Monitor & Workflow Chains (Phase 6) ──
            commands::health_monitor::engine_health_check_services,
            commands::health_monitor::engine_health_update_service,
            commands::health_monitor::engine_health_trigger_reauth,
            commands::health_monitor::engine_health_list_chains,
            commands::health_monitor::engine_health_save_chain,
            commands::health_monitor::engine_health_toggle_chain,
            commands::health_monitor::engine_health_delete_chain,
            // ── Integrations Management (Phase 7) ──
            commands::integrations::engine_integrations_list_connected,
            commands::integrations::engine_integrations_get_connected,
            commands::integrations::engine_integrations_connect,
            commands::integrations::engine_integrations_disconnect,
            commands::integrations::engine_integrations_touch,
            commands::integrations::engine_integrations_overview,
            // ── MCP Servers (Phase E) ──
            commands::mcp::engine_mcp_list_servers,
            commands::mcp::engine_mcp_save_server,
            commands::mcp::engine_mcp_remove_server,
            commands::mcp::engine_mcp_connect,
            commands::mcp::engine_mcp_disconnect,
            commands::mcp::engine_mcp_status,
            commands::mcp::engine_mcp_refresh_tools,
            commands::mcp::engine_mcp_connect_all,
            // ── Squads ──
            commands::squad::engine_squads_list,
            commands::squad::engine_squad_create,
            commands::squad::engine_squad_update,
            commands::squad::engine_squad_delete,
            commands::squad::engine_squad_add_member,
            commands::squad::engine_squad_remove_member,
            commands::squad::engine_agent_messages,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
